name: vec_gilang
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  ansicolor: ^2.0.2
  cached_network_image: ^3.3.1
  country_pickers: ^3.0.1
  device_info_plus: ^9.0.3
  dio: ^5.4.3+1
  dynamic_height_grid_view: ^0.0.4
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  talker_dio_logger: ^4.2.0
  webview_flutter: ^4.8.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
